### PR TITLE
Fixed plot_linear_regression_wave() not displaying plots on some devices

### PR DESCRIPTION
**Pull request by Dmium**
This probably extends to other functions but tbh this was the only one I needed at the time. Can add support on other methods later.

Tested for devices that worked already and broken device.

### CODE REVIEW

**Comment by FreyaRhianna** [comment]
For the devices that this method worked on previously, this updated version is functionally identical.

**Comment by amueller** [comment]
This has nothing do to with devices really. I would rather not do this, as it makes it harder to alter the plot afterwards.
The code is supposed to be run in a jupyter notebook with ``matplotlib inline`` enabled, as explained in the book. If you run this as a script, you have to run ``plt.show()`` manually, as I also explained in the book.

**Comment by Dmium** [comment]
"%matplotlib inline" worked thanks for the suggestion. Not sure why this happened my graphs have always displayed fine without the use of libraries before now.

Thanks for your suggestion.

**Comment by amueller** [comment]
how did you run them? If you used my notebooks, they all included that line.

**Comment by Dmium** [comment]
Sorry I should've specified matplotlib (Not using mglearn) worked fine up till now without that line or a .show().

**Comment by amueller** [comment]
possibly something related to your matplotlibrc. They just retired the interactive mode, I think.

**Pull request closed without merging**
