### PR TITLE
Fix joblib.Memory no longer supports cachedir argument

### PR DESCRIPTION
**Pull request by jilv220**
https://github.com/amueller/mglearn/issues/23#issue-1403214489

### CODE REVIEW

**Comment by amueller** [comment]
Thank you for the fix. Can you maybe just remove the keyword instead of defining a variable? Also, does passing it positionally work for both the old and the new version?

**Comment by jilv220** [comment]
Seems it worked for both the old and the new version. 

I tested import mglearn with both joblib version 1.1.1 and 1.2.0.

**Comment by jilv220** [comment]
Sorry with the late reply. I was busy doing course works before.

**Comment by g-cqd** [comment]
Could this be pushed to the pip repository please ?

**Comment by amueller** [comment]
sorry for the slow response, should be fixed now, I'll upload it to pipy shortly.

**Pull request closed without merging**
