### PR TITLE
Require threadpoolctl.

### PR DESCRIPTION
**Pull request by iangow**

### CODE REVIEW

**Comment by amueller** [comment]
Thanks! Does not installing it lead to errors, or did you have threading issues?

**Comment by iangow** [comment]
Issues on import. See below.

```
igow@2009-Mac-Pro Downloads % sudo pip3 uninstall threadpoolctl   
Password:
WARNING: The directory '/Users/igow/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Found existing installation: threadpoolctl 2.1.0
Uninstalling threadpoolctl-2.1.0:
  Would remove:
    /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/threadpoolctl-2.1.0.dist-info/*
    /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/threadpoolctl.py
Proceed (y/n)? y
  Successfully uninstalled threadpoolctl-2.1.0
igow@2009-Mac-Pro Downloads % python3
Python 3.8.5 (default, Jul 21 2020, 18:31:18) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mglearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mglearn/__init__.py", line 1, in <module>
    from . import plots
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mglearn/plots.py", line 18, in <module>
    from .plot_agglomerative import plot_agglomerative, plot_agglomerative_algorithm
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mglearn/plot_agglomerative.py", line 4, in <module>
    from sklearn.cluster import AgglomerativeClustering
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/cluster/__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/cluster/_spectral.py", line 18, in <module>
    from ._kmeans import k_means
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 18, in <module>
    from threadpoolctl import threadpool_limits
ModuleNotFoundError: No module named 'threadpoolctl'
>>> exit()
igow@2009-Mac-Pro Downloads % sudo pip3 install threadpoolctl 
WARNING: The directory '/Users/igow/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting threadpoolctl
  Downloading threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Installing collected packages: threadpoolctl
Successfully installed threadpoolctl-2.1.0
igow@2009-Mac-Pro Downloads % python3                        
Python 3.8.5 (default, Jul 21 2020, 18:31:18) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mglearn
>>> 
```

**Comment by amueller** [comment]
Ok, that means sklearn requires it, but sklearn also depends on it, right? So if you ``pip install scikit-learn`` that will install threadpoolctl.

**Comment by iangow** [comment]
Actually, that's correct. I must have an installation (not `pip`-installed) of `scikit-learn` that didn't require `threadpoolctl`. When I try to `pip`-install `scikit-learn`, it does grab `threadpoolctl`. So I guess this is really an issue for MacPorts (where I got my version of `scikit-learn`).

```
igow@2009-Mac-Pro Downloads % sudo pip3 uninstall threadpoolctl
Password:
WARNING: The directory '/Users/igow/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Found existing installation: threadpoolctl 2.1.0
Uninstalling threadpoolctl-2.1.0:
  Would remove:
    /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/threadpoolctl-2.1.0.dist-info/*
    /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/threadpoolctl.py
Proceed (y/n)? y
  Successfully uninstalled threadpoolctl-2.1.0
igow@2009-Mac-Pro Downloads % sudo pip3 install scikit-learn --force-reinstall
WARNING: The directory '/Users/igow/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting scikit-learn
  Downloading scikit_learn-0.23.2-cp38-cp38-macosx_10_9_x86_64.whl (7.2 MB)
     |████████████████████████████████| 7.2 MB 5.5 MB/s 
Collecting joblib>=0.11
  Downloading joblib-0.16.0-py3-none-any.whl (300 kB)
     |████████████████████████████████| 300 kB 56.1 MB/s 
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting numpy>=1.13.3
  Downloading numpy-1.19.1-cp38-cp38-macosx_10_9_x86_64.whl (15.3 MB)
     |████████████████████████████████| 15.3 MB 52.2 MB/s 
Collecting scipy>=0.19.1
  Downloading scipy-1.5.2-cp38-cp38-macosx_10_9_x86_64.whl (28.9 MB)
     |████████████████████████████████| 28.9 MB 17.0 MB/s 
Installing collected packages: joblib, threadpoolctl, numpy, scipy, scikit-learn
  Attempting uninstall: joblib
    Found existing installation: joblib 0.16.0
    Uninstalling joblib-0.16.0:
      Successfully uninstalled joblib-0.16.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.1
    Uninstalling numpy-1.19.1:
      Successfully uninstalled numpy-1.19.1
  Attempting uninstall: scipy
    Found existing installation: scipy 1.5.2
    Uninstalling scipy-1.5.2:
      Successfully uninstalled scipy-1.5.2
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.23.1
ERROR: Cannot uninstall 'scikit-learn'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by amueller** [comment]
Yeah, I think it is either an issue with the distribution you  used, or with the way it was installed. There's many things that can go wrong when upgrading libraries :-/ But I don't think it should be necessary to add to mglearn.

**Comment by iangow** [comment]
Agreed. Thanks. I filed an issue with MacPorts, which is missing the dependency, and replaced my `scikit-learn` with a `pip`-installed version. Sorry for the bother.

```
igow@2009-Mac-Pro Downloads % sudo port uninstall py38-scikit-learn
Password:
--->  Deactivating py38-scikit-learn @0.23.1_0
--->  Cleaning py38-scikit-learn
--->  Uninstalling py38-scikit-learn @0.23.1_0
--->  Cleaning py38-scikit-learn
igow@2009-Mac-Pro Downloads % sudo pip3 install scikit-learn 
WARNING: The directory '/Users/igow/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting scikit-learn
  Downloading scikit_learn-0.23.2-cp38-cp38-macosx_10_9_x86_64.whl (7.2 MB)
     |████████████████████████████████| 7.2 MB 4.3 MB/s 
Requirement already satisfied: joblib>=0.11 in /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scikit-learn) (0.16.0)
Requirement already satisfied: numpy>=1.13.3 in /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scikit-learn) (1.19.1)
Requirement already satisfied: scipy>=0.19.1 in /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scikit-learn) (1.5.2)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Installing collected packages: threadpoolctl, scikit-learn
Successfully installed scikit-learn-0.23.2 threadpoolctl-2.1.0
igow@2009-Mac-Pro Downloads % python3                         
Python 3.8.5 (default, Jul 21 2020, 18:31:18) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mglearn
```

**Comment by amueller** [comment]
all good!

**Pull request closed without merging**
