### PR TITLE
Issue #5 fix

### PR DESCRIPTION
**Pull request by idahogray**
I ran into the same issue as described in #5 and have made the suggested changes locally. They allowed me to import the mglearn library but I haven't tested the functionality associated with those imports. Please let me know if there is anything else you need.

### CODE REVIEW

**Comment by amueller** [comment]
This is not the right fix. The right fix is likely using imageio:
https://github.com/amueller/mglearn/issues/8#issuecomment-416813859

**Comment by idahogray** [comment]
I have updated my pull request with the changes suggested by ebunt. I haven't done any testing.

**Comment by amueller** [comment]
That's what I get for not having any unit tests, I guess. It also needs to be added to setup.py but really I need to add unit tests to this repo.
Any chance you wanna help ;)

**Comment by idahogray** [comment]
I noticed that today and will get it fixed.

I don't want to make any promises but I might be able to help. Let me see what my schedule looks like coming up.

**Comment by amueller** [comment]
thanks :)

**Pull request merged**
